name: Update CONTRIBUTORS file

on:
  push:
    branches: [ development ]
    paths:
      - './src/**/*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: minicli/action-contributors@v3
        name: "Update a projects CONTRIBUTORS file"
        env:
          CONTRIB_REPOSITORY: ${{ github.repository }}
          CONTRIB_OUTPUT_FILE: 'CONTRIBUTORS.md'

      - run: echo "$(<CONTRIBUTORS.md)"

      - name: Commit changes
        uses: test-room-7/action-update-file@v1
        with:
          file-path: 'CONTRIBUTORS.md'
          commit-msg: '[actions] update contributors'
          github-token: ${{ secrets.WORKFLOW_TOKEN }}